#!/bin/sh
echo ...

EXECUTABLE_NAME=MeshPi
EXECUTABLE_NAME_DEBUG=$EXECUTABLE_NAME-DEBUG
EXECUTABLE_NAME_RELEASE=$EXECUTABLE_NAME-RELEASE

BUILD_PATH=build

SOURCE_PATH=src
SOURCE_FILES="$SOURCE_PATH/MeshEngine.cpp $SOURCE_PATH/RaspberryPi/raspberrypi_platform_layer.cpp"

INCLUDE_DIRECTORIES="-I./src/ -I/opt/vc/include/ -I./libs/ilclient -I./libs/vgfont -I./libs/revision"

LINK_LIBRARIES="-L/opt/vc/lib/  -lbrcmGLESv2 -lbrcmEGL -lopenmaxil -lbcm_host -lvcos -lvchiq_arm -lpthread -lrt -lm"

DEFINED_MACROS="-DRASPBERRY_PI -DSTANDALONE -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -DTARGET_POSIX -D_LINUX -fPIC -DPIC -D_REENTRANT -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -U_FORTIFY_SOURCE -Wall -g -DHAVE_LIBOPENMAX=2 -DOMX -DOMX_SKIP64BIT -ftree-vectorize -pipe -DUSE_EXTERNAL_OMX -DHAVE_LIBBCM_HOST -DUSE_EXTERNAL_LIBBCM_HOST -DUSE_VCHIQ_ARM -Wno-psabi"
DEFINED_MACROS_DEBUG="$DEFINED_MACROS -DDEBUG"
DEFINED_MACROS_RELEASE="$DEFINED_MACROS -DRELEASE"


echo 'building' $EXECUTABLE_NAME_DEBUG
g++ $DEFINED_MACROS_DEBUG  $INCLUDE_DIRECTORIES -g $SOURCE_FILES -o $BUILD_PATH/$EXECUTABLE_NAME_DEBUG $LINK_LIBRARIES
echo $EXECUTABLE_NAME_DEBUG 'build complete!'
echo ...

echo 'building' $EXECUTABLE_NAME_RELEASE
g++ $DEFINED_MACROS_RELEASE $INCLUDE_DIRECTORIES $SOURCE_FILES -O3 -o $BUILD_PATH/$EXECUTABLE_NAME_RELEASE $LINK_LIBRARIES
echo $EXECUTABLE_NAME_RELEASE 'build complete!'